name: Format and Tidy
on: [push]
jobs:
  lint:
    strategy:
      matrix:
        check: [clang-tidy, clang-format]
    runs-on: ubuntu-latest
    container: silkeh/clang:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites"
        run:  apt update && apt install -y meson ninja-build python-is-python3
      - name: Configure
        run: meson build -Denable-tests=false -Denable-examples=false
      - name: ${{ matrix.check }}
        run: ninja -C build ${{ matrix.check }}
